
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(350, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botom_point = QtWidgets.QPushButton(self.centralwidget)
        self.botom_point.setGeometry(QtCore.QRect(0, 350, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_point.setFont(font)
        self.botom_point.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_point.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_point.setObjectName("botom_point")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(217, 240, 231);")
        self.label.setObjectName("label")
        self.botom_0 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_0.setGeometry(QtCore.QRect(100, 350, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_0.setFont(font)
        self.botom_0.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_0.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_0.setObjectName("botom_0")
        self.botom_divide = QtWidgets.QPushButton(self.centralwidget)
        self.botom_divide.setGeometry(QtCore.QRect(300, 350, 50, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_divide.setFont(font)
        self.botom_divide.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_divide.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_divide.setObjectName("botom_divide")
        self.botom_equal = QtWidgets.QPushButton(self.centralwidget)
        self.botom_equal.setGeometry(QtCore.QRect(200, 350, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_equal.setFont(font)
        self.botom_equal.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_equal.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_equal.setObjectName("botom_equal")
        self.botom_3 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_3.setGeometry(QtCore.QRect(200, 250, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_3.setFont(font)
        self.botom_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_3.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_3.setObjectName("botom_3")
        self.botom_plus = QtWidgets.QPushButton(self.centralwidget)
        self.botom_plus.setGeometry(QtCore.QRect(300, 250, 50, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_plus.setFont(font)
        self.botom_plus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_plus.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_plus.setObjectName("botom_plus")
        self.botom_1 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_1.setGeometry(QtCore.QRect(0, 250, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_1.setFont(font)
        self.botom_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_1.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_1.setObjectName("botom_1")
        self.botom_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_2.setGeometry(QtCore.QRect(100, 250, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_2.setFont(font)
        self.botom_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_2.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_2.setObjectName("botom_2")
        self.botom_5 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_5.setGeometry(QtCore.QRect(100, 150, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_5.setFont(font)
        self.botom_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_5.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_5.setObjectName("botom_5")
        self.botom_6 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_6.setGeometry(QtCore.QRect(200, 150, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_6.setFont(font)
        self.botom_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_6.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_6.setObjectName("botom_6")
        self.botom_minus = QtWidgets.QPushButton(self.centralwidget)
        self.botom_minus.setGeometry(QtCore.QRect(300, 150, 50, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_minus.setFont(font)
        self.botom_minus.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_minus.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_minus.setObjectName("botom_minus")
        self.botom_4 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_4.setGeometry(QtCore.QRect(0, 150, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_4.setFont(font)
        self.botom_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_4.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_4.setObjectName("botom_4")
        self.botom_7 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_7.setGeometry(QtCore.QRect(0, 50, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_7.setFont(font)
        self.botom_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_7.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_7.setObjectName("botom_7")
        self.botom_9 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_9.setGeometry(QtCore.QRect(200, 50, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_9.setFont(font)
        self.botom_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_9.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_9.setObjectName("botom_9")
        self.botom_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.botom_multiply.setGeometry(QtCore.QRect(300, 50, 50, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_multiply.setFont(font)
        self.botom_multiply.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_multiply.setStyleSheet("background-color: rgb(255, 216, 216);")
        self.botom_multiply.setObjectName("botom_multiply")
        self.botom_8 = QtWidgets.QPushButton(self.centralwidget)
        self.botom_8.setGeometry(QtCore.QRect(100, 50, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botom_8.setFont(font)
        self.botom_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.botom_8.setStyleSheet("background-color: rgb(241, 255, 167);")
        self.botom_8.setObjectName("botom_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.botom_point.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "0"))
        self.botom_0.setText(_translate("MainWindow", "0"))
        self.botom_divide.setText(_translate("MainWindow", "/"))
        self.botom_equal.setText(_translate("MainWindow", "="))
        self.botom_3.setText(_translate("MainWindow", "3"))
        self.botom_plus.setText(_translate("MainWindow", "+"))
        self.botom_1.setText(_translate("MainWindow", "1"))
        self.botom_2.setText(_translate("MainWindow", "2"))
        self.botom_5.setText(_translate("MainWindow", "5"))
        self.botom_6.setText(_translate("MainWindow", "6"))
        self.botom_minus.setText(_translate("MainWindow", "-"))
        self.botom_4.setText(_translate("MainWindow", "4"))
        self.botom_7.setText(_translate("MainWindow", "7"))
        self.botom_9.setText(_translate("MainWindow", "9"))
        self.botom_multiply.setText(_translate("MainWindow", "*"))
        self.botom_8.setText(_translate("MainWindow", "8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
